### ISSUE TITLE
ND4J is probably missing dependencies

### ISSUE THREAD

**Issue by Yu-Hang** [deeplearning4j/nd4j#2310]
#### Issue Description

 Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
                                                                                at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
                                                                                at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
                                                                                at org.nd4j.nativeblas.NativeOpsHolder.getInstance(NativeOpsHolder.java:58) 
                                                                                at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:41) 
                                                                                at java.lang.Class.newInstance(Native Method) 
                                                                                at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5784) 
                                                                                at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5694) 
                                                                                at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:184) 
                                                                                at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:2319) 
                                                                                at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:216) 
                                                                                at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:167) 
                                                                                at gov.nih.nlm.malaria_screener.Cells.<init>(Cells.java:95) 
                                                                                at gov.nih.nlm.malaria_screener.CameraActivity.ProcessImage(CameraActivity.java:1090) 
                                                                                at gov.nih.nlm.malaria_screener.CameraActivity$8.run(CameraActivity.java:860) 
                                                                                at java.lang.Thread.run(Thread.java:762) 
                                                                             Caused by: java.lang.NoSuchMethodError: No static method totalCores()I in class Lorg/bytedeco/javacpp/Loader; or its super classes (declaration of 'org.bytedeco.javacpp.Loader' appears in /data/app/gov.nih.nlm.malaria_screener-1/base.apk:classes13.dex)
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.0
* platform information (OS, etc) : Android 

#### Contributing

The code I'm running:

 ```
   MultiLayerNetwork model;
    BaseImageLoader imgLoader;
    ByteArrayOutputStream bos;

    public long NNprocessingTime = 0;

    public Cells(Mat mask, Mat oriSizeImage, Context context, Mat RMask) {

        File file = new File(Environment.getExternalStorageDirectory() + "/trained_model.zip");
        if (!file.exists()) {
            InputStream inputStream = context.getResources().openRawResource(context.getResources().getIdentifier("trained_model", "raw", context.getPackageName()));

            try {
                OutputStream outputStream = new FileOutputStream(file);
                IOUtils.copy(inputStream, outputStream);
                outputStream.close();

            } catch (IOException e) {
                e.printStackTrace();
            }

        }

        try {
            model = ModelSerializer.restoreMultiLayerNetwork(file);
        } catch (IOException e) {
            e.printStackTrace();
        }

```
Gradle:

```
android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "gov.nih.nlm.malaria_screener"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 6 // start from 1
        versionName "1.3.2" // start from 1.0
        multiDexEnabled true
        jackOptions { // for Java 1.8
            enabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions { // for unsigned release build error on Time and Date picker
        checkReleaseBuilds false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'org/bytedeco/javacpp/windows-x86/msvcp120.dll'
        exclude 'org/bytedeco/javacpp/windows-x86_64/msvcp120.dll'
        exclude 'org/bytedeco/javacpp/windows-x86/msvcr120.dll'
        exclude 'org/bytedeco/javacpp/windows-x86_64/msvcr120.dll'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/INDEX.LIST'
    }
}

dependencies {
    compile files('libs/GraphView-4.0.1.jar')
    compile files('libs/AndroidSwipeLayout-v1.1.8.jar')
    compile 'com.dropbox.core:dropbox-core-sdk:2.0.1'
    compile files('libs/dropbox-android-sdk-1.6.3.jar')
    compile files('libs/json_simple-1.1.jar')
    compile files('libs/eventbus-3.0.0.jar')
    compile files('libs/glide-3.7.0.jar')
    compile files('libs/flickrj-android-2.0.0.jar')
    compile project(':libraries:opencv')
//    compile 'org.deeplearning4j:deeplearning4j-core:0.7.2'
//    compile 'org.nd4j:nd4j-native:0.7.2'
//    compile 'org.nd4j:nd4j-native:0.7.2:android-x86'
//    compile 'org.nd4j:nd4j-native:0.7.2:android-arm'
    compile 'org.deeplearning4j:deeplearning4j-core:0.8.0'
    compile 'org.nd4j:nd4j-native:0.8.0'
    compile 'org.nd4j:nd4j-native:0.8.0:android-x86'
    compile 'org.nd4j:nd4j-native:0.8.0:android-arm'
    compile 'org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-x86'
    compile 'org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-arm'
    annotationProcessor 'org.projectlombok:lombok:1.16.10'
    compile project(':mysql-connector-java-5.1.43-bin')
    compile 'com.android.support:appcompat-v7:25.4.0'
    compile 'com.android.support:design:25.4.0'
    compile 'com.android.support:cardview-v7:25.4.0'
    compile 'com.android.support:support-v13:25.4.0'
    compile 'com.android.support:support-v4:25.4.0'
    compile 'com.android.support:recyclerview-v7:25.4.0'
    compile 'com.github.amlcurran.showcaseview:library:5.4.3'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
}

```

**Comment by saudet** [comment]
Isn't this the same as issue #1922?

**Comment by Yu-Hang** [comment]
I don't think so. The solution from #1922 worked when i was using 0.7.2. But now I'm using 0.8.0 (this is the only thing I changed in my code ever since the issue #1922 was solved). And the error description is actually different from before @saudet

**Comment by saudet** [comment]
Yes the message is different, but it just means it wasn't able to load the native libraries, which are probably missing from your APK. In any case, you should be trying with version 0.9.1. :)

**Comment by Yu-Hang** [comment]
I simply changed all 0.8.0 to 0.9.1.. And now I'm getting the error:
```
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```
Some people say to add `multiDexEnabled true` solved their problem. But as you can see, I already have that in my build file. And I also tried clean and rebuild. Please help. @saudet

**Comment by saudet** [comment]
That's apparently an issue with Android Studio 3.0:
https://github.com/deeplearning4j/deeplearning4j/issues/4330
Please try to use version 2.3.3 until we figure out what dependency it doesn't like...

**Comment by AvielNiego** [comment]
Using this dependancies fixed the `Unable to merge dex` for me
```
annotationProcessor 'org.projectlombok:lombok:1.16.16'
implementation 'junit:junit:4.12'
implementation 'org.bytedeco:javacpp:1.3.3'
implementation "org.nd4j:nd4j-native-platform:${nd4j_version}"
```

But I still get the 
`Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html`

**Comment by saudet** [comment]
@AvielNiego Be sure to read https://deeplearning4j.org/android

**Comment by saudet** [comment]
@AvielNiego And this too: https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29 It's probably a problem with your device, so make sure to use ReLinker. @jrmerwin will be documenting all this properly.

**Comment by jrmerwin** [comment]
@AvielNiego Try including these dependencies, they should suppress that error.
```java
Implementation 'org.deeplearning4j:deeplearning4j-nn:0.9.1'
Implementation 'org.nd4j:nd4j-native:0.9.1'
Implementation 'org.nd4j:nd4j-native:0.9.1:android-x86'
Implementation 'org.nd4j:nd4j-native:0.9.1:android-arm'
Implementation 'org.bytedeco.javacpp-presets:systems-platform:1.4'
Implementation 'org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-x86'
Implementation 'org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-arm'
```

**Comment by javaddict** [comment]
Try this:
```gradle
implementation ('org.nd4j:nd4j-native-platform:0.9.1') {
    exclude group: 'com.github.stephenc.findbugs', module: 'findbugs-annotations'
}
implementation 'org.tensorflow:tensorflow-android:1.6.0'
```

**Comment by andylamp** [comment]
any progress regarding this issue?

**Comment by agibsonccc** [comment]
I'm not sure there is any "progress" to be made? If you read it was just a docs issue. I'm closing this.

**Comment by saudet** [comment]
@andylamp There is new documentation here:
https://deeplearning4j.org/android-DL4JImageRecognitionDemo
https://deeplearning4j.org/android-DL4JIrisClassifierDemo
https://deeplearning4j.org/android-Prereqs%20and%20Configuration
But it isn't linked in from the main https://deeplearning4j.org/android page...

@jrmerwin Could you update the main android.md page with updated content as well as links to the new content as appropriate? Thanks!
